name: ECR Sandbox Cleanup
description: A GitHub action to delete ECR sandbox releases that do not exist in Git as branches.
branding:
  icon: check-circle
  color: green
inputs:
  ecr-image:
    description: The full image path, without ECR domain
    required: true
  ecr-domain:
    description: The ECR Domain

runs:
  using: 'composite'
  steps:
    - id: registry
      name: Parse Registry ID
      shell: bash
      run: echo ::set-output name=id::$(echo "${{ inputs.ecr-domain }}" | cut -d. -f1)

    - name: Read Tags
      shell: bash
      run: |
        echo "Sandbox Tags:"
        (git ls-remote | grep -o 'releases/sandbox/.*' | sed 's|releases/sandbox/|sandbox-|g') || true | tee sandbox-tags.txt
        echo "sandbox-latest" >> sandbox-tags.txt

    - name: Clean up S3 path
      shell: bash
      run: |
        echo "ECR Tags:"
        ecrTags=$(aws ecr list-images --registry-id ${{ steps.registry.outputs.id }} --repository-name=${{ inputs.ecr-image }} --filter tagStatus=TAGGED | jq -r '.imageIds[].imageTag' | (grep -E '^sandbox-' || true) | sort)
        echo "$ecrTags"
        for releaseTag in $ecrTags
        do
          if [[ -z "$(grep -E "^$releaseTag\$" sandbox-tags.txt)" ]]
          then
            echo "Deleting $releaseTag"
            aws ecr batch-delete-image --registry-id="${{ steps.registry.outputs.id }}" --repository-name ${{ inputs.ecr-image }} --image-ids "imageTag=$releaseTag"
          fi
        done
